### ISSUE TITLE
Crash when breaking a chest

### ISSUE THREAD

**Issue by ShainCasterway** [ZestyBlaze/Gilded-Netherite#2]
Just started a new world and when breaking a chest the game crashes. here's the report

Description: Unexpected error

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4838 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_2248.method_9576(class_2248.java:500)
	at net.minecraft.class_636.method_2899(class_636.java:125)
	at net.minecraft.class_636.method_2902(class_636.java:250)
	at net.optifine.override.PlayerControllerOF.method_2902(PlayerControllerOF.java:65)
	at net.minecraft.class_310.method_1590(class_310.java:1553)
	at net.minecraft.class_310.method_1508(class_310.java:1912)
	at net.minecraft.class_310.method_1574(class_310.java:1729)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_4838::method_24719(Lnet/minecraft/class_1309;)Z has incompatible changes at opcode 67 in callback gilded.mixins.json:GildedGoldStat->@Inject::wearsGoldArmor(Lnet/minecraft/class_1309;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/lang/Iterable;)V from mod gilded.
 Expected: [Ljava/lang/Iterable;]
    Found: []
Available: []
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:545)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_2248.method_9576(class_2248.java:500)
	at net.minecraft.class_636.method_2899(class_636.java:125)
	at net.minecraft.class_636.method_2902(class_636.java:250)
	at net.optifine.override.PlayerControllerOF.method_2902(PlayerControllerOF.java:65)
	at net.minecraft.class_310.method_1590(class_310.java:1553)
	at net.minecraft.class_310.method_1508(class_310.java:1912)

-- Affected level --
Details:
	All players: 1 total; [class_746['ShainCasterway'/217, l='ClientLevel', x=35.24, y=65.00, z=117.90]]
	Chunk stats: 529, 325
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,69,112), Section: (at 0,5,0 in 2,4,7; chunk contains blocks 32,-64,112 to 47,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1286 game time, 1286 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:517)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ZestyBlaze** [comment]
Hmmm interesting. I'll take a look at that. Which version is that for. 1.18 or 1.17?

**Comment by ShainCasterway** [comment]
1.18.1

**Comment by ShainCasterway** [comment]
luckily i'll take a while to get netherite so hopefully this bug will not effect my gameplay
(ty for the quick response btw)

**Comment by ZestyBlaze** [comment]
No problem, I've got work in an hour so I'll take a quick look at the code and see if I can spot any immediate problems and fixes, I'm guessing this was a problem when the mod was ported forward

**Comment by ZestyBlaze** [comment]
At this point in time I'm very confused. The crash states something that shouldn't be the case, I've been able to replicate it and I've looked through the code with no obvious errors, it saying something doesn't exist when it does so it's going to need more extensive testing when I'm home

**Comment by ShainCasterway** [comment]
alright, hope you can fix it!

**Comment by ZestyBlaze** [comment]
Apologies for this! For now I've removed the mod from Curseforge, I'd recommend removing the mod and I'll attempt at rewritting the code to fix it!

**Comment by ShainCasterway** [comment]
oh, alright. as i've said anyway, it will take me a while to get netherite so it may not even be a problem :)
gl rewriting the code!
oh also, is there a possibility to also add compatibility with Armor Chroma? https://www.curseforge.com/minecraft/mc-mods/armor-chroma-for-fabric

**Comment by ZestyBlaze** [comment]
Fixed in newest version
